# Generated by Django 4.1.4 on 2023-11-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employeeid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Employeename', models.TextField(max_length=100)),
                ('Employeephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Itemid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Itemname', models.TextField(max_length=100)),
                ('Itemquantity', models.FloatField()),
                ('Itemdescription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Userid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Username', models.TextField(max_length=100)),
                ('Useremail', models.EmailField(max_length=254)),
                ('Userphone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datebooking', models.DateField()),
                ('Datereturn', models.DateField()),
                ('Itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Annur.item')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Annur.user')),
            ],
        ),
    ]
