# Generated by Django 4.1.4 on 2023-11-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Annur', '0002_rename_user_cususers_alter_booking_userid_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Itemid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Userid',
        ),
        migrations.DeleteModel(
            name='CusUsers',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
